server:
  port: 8080

mail:
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  tls: true
  username: xx@gmail.com
  password: xx
  properties:
    mail.smtp:
      auth: true
      starttls.enable: true

cron:
  available-date:
    checker: 0 */5 * ? * *